name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  backend-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      working-directory: ./backend
      run: |
        docker build -t course-copilot-backend:${{ github.sha }} .
        docker tag course-copilot-backend:${{ github.sha }} course-copilot-backend:latest


    - name: Login to GitHub Container Registry (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Registry (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./backend
      run: |
        docker tag course-copilot-backend:latest ghcr.io/${{ github.repository_owner }}/course-copilot-backend:latest
        docker tag course-copilot-backend:latest ghcr.io/${{ github.repository_owner }}/course-copilot-backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/course-copilot-backend:latest
        docker push ghcr.io/${{ github.repository_owner }}/course-copilot-backend:${{ github.sha }}